import DietCard from "../components/diet/DietCard";
const diets = [
  {
    name: "Dieta 1",
    meals: [
      {
        time: "07:00",
        items: [
          {
            food: "Omelete",
            quantity: "120g",
            kcal: 140,
            protein: 12,
            carbs: 1,
            fat: 10,
            fiber: 0,
            sodium: 200,
            sugar: 0,
            iron: 1.2,
            calcium: 50,
            potassium: 100,
          },
          {
            food: "Suco de laranja",
            quantity: "240g",
            kcal: 110,
            protein: 2,
            carbs: 26,
            fat: 0,
            fiber: 0.5,
            sodium: 2,
            sugar: 21,
            iron: 0.2,
            calcium: 27,
            potassium: 250,
          },
          {
            food: "Pão integral",
            quantity: "60g",
            kcal: 130,
            protein: 5,
            carbs: 23,
            fat: 2,
            fiber: 3,
            sodium: 170,
            sugar: 3,
            iron: 1,
            calcium: 40,
            potassium: 80,
          },
        ],
      },
      {
        time: "10:00",
        items: [
          {
            food: "Banana",
            quantity: "120g",
            kcal: 90,
            protein: 1,
            carbs: 23,
            fat: 0.3,
            fiber: 2.6,
            sodium: 1,
            sugar: 12,
            iron: 0.3,
            calcium: 5,
            potassium: 450,
          },
          {
            food: "Iogurte natural",
            quantity: "150g",
            kcal: 100,
            protein: 8,
            carbs: 7,
            fat: 5,
            fiber: 0,
            sodium: 50,
            sugar: 7,
            iron: 0.1,
            calcium: 150,
            potassium: 200,
          },
          {
            food: "Granola",
            quantity: "30g",
            kcal: 120,
            protein: 3,
            carbs: 20,
            fat: 4,
            fiber: 2.5,
            sodium: 10,
            sugar: 8,
            iron: 0.5,
            calcium: 20,
            potassium: 100,
          },
        ],
      },
      {
        time: "13:00",
        items: [
          {
            food: "Arroz integral",
            quantity: "195g",
            kcal: 215,
            protein: 5,
            carbs: 45,
            fat: 2,
            fiber: 3.5,
            sodium: 5,
            sugar: 0,
            iron: 1.2,
            calcium: 10,
            potassium: 80,
          },
          {
            food: "Peito de frango",
            quantity: "150g",
            kcal: 250,
            protein: 40,
            carbs: 0,
            fat: 5,
            fiber: 0,
            sodium: 70,
            sugar: 0,
            iron: 0.9,
            calcium: 15,
            potassium: 300,
          },
          {
            food: "Brócolis",
            quantity: "156g",
            kcal: 55,
            protein: 5,
            carbs: 11,
            fat: 0.6,
            fiber: 5,
            sodium: 30,
            sugar: 2,
            iron: 1,
            calcium: 43,
            potassium: 287,
          },
        ],
      },
      {
        time: "13:00",
        items: [
          {
            food: "Arroz integral",
            quantity: "195g",
            kcal: 215,
            protein: 5,
            carbs: 45,
            fat: 2,
            fiber: 3.5,
            sodium: 5,
            sugar: 0,
            iron: 1.2,
            calcium: 10,
            potassium: 80,
          },
          {
            food: "Peito de frango",
            quantity: "150g",
            kcal: 250,
            protein: 40,
            carbs: 0,
            fat: 5,
            fiber: 0,
            sodium: 70,
            sugar: 0,
            iron: 0.9,
            calcium: 15,
            potassium: 300,
          },
          {
            food: "Brócolis",
            quantity: "156g",
            kcal: 55,
            protein: 5,
            carbs: 11,
            fat: 0.6,
            fiber: 5,
            sodium: 30,
            sugar: 2,
            iron: 1,
            calcium: 43,
            potassium: 287,
          },
        ],
      },
      {
        time: "13:00",
        items: [
          {
            food: "Arroz integral",
            quantity: "195g",
            kcal: 215,
            protein: 5,
            carbs: 45,
            fat: 2,
            fiber: 3.5,
            sodium: 5,
            sugar: 0,
            iron: 1.2,
            calcium: 10,
            potassium: 80,
          },
          {
            food: "Peito de frango",
            quantity: "150g",
            kcal: 250,
            protein: 40,
            carbs: 0,
            fat: 5,
            fiber: 0,
            sodium: 70,
            sugar: 0,
            iron: 0.9,
            calcium: 15,
            potassium: 300,
          },
          {
            food: "Brócolis",
            quantity: "156g",
            kcal: 55,
            protein: 5,
            carbs: 11,
            fat: 0.6,
            fiber: 5,
            sodium: 30,
            sugar: 2,
            iron: 1,
            calcium: 43,
            potassium: 287,
          },
        ],
      },
      {
        time: "13:00",
        items: [
          {
            food: "Arroz integral",
            quantity: "195g",
            kcal: 215,
            protein: 5,
            carbs: 45,
            fat: 2,
            fiber: 3.5,
            sodium: 5,
            sugar: 0,
            iron: 1.2,
            calcium: 10,
            potassium: 80,
          },
          {
            food: "Peito de frango",
            quantity: "150g",
            kcal: 250,
            protein: 40,
            carbs: 0,
            fat: 5,
            fiber: 0,
            sodium: 70,
            sugar: 0,
            iron: 0.9,
            calcium: 15,
            potassium: 300,
          },
          {
            food: "Brócolis",
            quantity: "156g",
            kcal: 55,
            protein: 5,
            carbs: 11,
            fat: 0.6,
            fiber: 5,
            sodium: 30,
            sugar: 2,
            iron: 1,
            calcium: 43,
            potassium: 287,
          },
        ],
      },
    ],
  },
];
function DietPage() {
  return (
    <main className="min-h-screen bg-graphite-black flex flex-col py-10 gap-8 items-center">
      {diets.map((diet, index) => (
        <DietCard key={index} diet={diet} />
      ))}
    </main>
  );
}

export default DietPage;
